#!/bin/bash
#PBS -S /bin/bash
#PBS -l walltime=96:00:00,nodes=1:ppn=2:gpu -q home-gibbs -A mgilson-gibbs
#BS -l walltime=96:00:00,nodes=1:ppn=3:gpu -q home
#BS -l walltime=08:00:00,nodes=1:ppn=3:gpu -q glean
#PBS -j oe -r n -m n -M shireham@gmail.com
#PBS -N TS-XXXX

source /home/henrikse/paprika_install/env.sh

cd $TMPDIR
cp -p $PBS_O_WORKDIR/restraints.in ./
python $PBS_O_WORKDIR/execute.py
sleep 2
rsync -au ./ $PBS_O_WORKDIR/




